python: can't open file '/tmp/gptme-evals-ylj47nda/hello.py': [Errno 2] No such file or directory
