python: can't open file '/tmp/gptme-evals-disuv1w2/prime.py': [Errno 2] No such file or directory
