python: can't open file '/tmp/gptme-evals-yhjiz8px/hello.py': [Errno 2] No such file or directory
