python: can't open file '/tmp/gptme-evals-c04zhowf/hello.py': [Errno 2] No such file or directory
