python: can't open file '/tmp/gptme-evals-n7gh14rm/hello.py': [Errno 2] No such file or directory
