python: can't open file '/tmp/gptme-evals-n60whx73/prime.py': [Errno 2] No such file or directory
