python: can't open file '/tmp/gptme-evals-ghrtu2m5/prime.py': [Errno 2] No such file or directory
