python: can't open file '/tmp/gptme-evals-midjuv9s/hello.py': [Errno 2] No such file or directory
