python: can't open file '/tmp/gptme-evals-bmv1a8gz/hello.py': [Errno 2] No such file or directory
